---
- name: Setup and install packages
  hosts: localhost
  become: yes

  tasks:
    - name: Copy sources.list
      copy:
        src: sources.list
        dest: /etc/apt/sources.list

    - name: Add i386 architecture
      command: dpkg --add-architecture i386

    - name: Add Mullvad keyring and repository
      ansible.builtin.shell: |
        curl -fsSLo /usr/share/keyrings/mullvad-keyring.asc https://repository.mullvad.net/deb/mullvad-keyring.asc
        echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/mullvad.list

    - name: Add LibreWolf keyring and repository
      ansible.builtin.shell: |
        wget -O- https://deb.librewolf.net/keyring.gpg | gpg --dearmor -o /usr/share/keyrings/librewolf.gpg
        distro=$(if echo " una bookworm vanessa focal jammy bullseye vera uma " | grep -q " $(lsb_release -sc) "; then lsb_release -sc; else echo focal; fi)
        tee /etc/apt/sources.list.d/librewolf.sources << EOF > /dev/null
        Types: deb
        URIs: https://deb.librewolf.net
        Suites: $distro
        Components: main
        Architectures: amd64
        Signed-By: /usr/share/keyrings/librewolf.gpg
        EOF

    - name: Add Brave Browser keyring and repository
      ansible.builtin.shell: |
        curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install packages from packages.txt
      apt:
        name: "{{ item }}"
        state: present
      with_file:
        - packages.txt

    - name: Install wget and curl
      apt:
        name:
          - wget
          - curl
        state: present

    - name: Copy bashrc
      copy:
        src: bashrc
        dest: "{{ ansible_env.HOME }}/.bashrc"

    - name: Install Rust
      shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

    - name: Install Rust crates
      shell: cargo install --locked {{ item }}
      with_items:
        - bat
        - choose
        - exa
        - lsd
        - git-delta
        - du-dust
        - broot
        - fd-find
        - ripgrep
        - sd
        - bottom
        - gping
        - procs
        - zoxide
        - dns-doge
        - mcfly
        - xh
        - hyperfine
        - mdbook
        - "mdbook mdbook-image-size"
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

    - name: Install Neovim
      shell: |
        cd /tmp
        git clone https://github.com/neovim/neovim && cd neovim
        git checkout stable
        make CMAKE_BUILD_TYPE=RelWithDebInfo
        cd build && cpack -G DEB && dpkg -i nvim-linux64.deb

    - name: Install LunarVim
      shell: LV_BRANCH='release-1.4/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.4/neovim-0.9/utils/installer/install.sh)

    - name: Install Nerd Fonts
      shell: |
        cd /tmp
        git clone --depth=1 https://github.com/ryanoasis/nerd-fonts.git
        ./nerd-fonts/install.sh

    - name: Install VirtualBox
      shell: |
        cd /tmp
        wget 'https://download.virtualbox.org/virtualbox/7.0.20/virtualbox-7.0_7.0.20-163906~Debian~bookworm_amd64.deb'
        dpkg -i ./*virtualbox*

